version: '3.1'

services:

  db:
    image: mariadb:11.7
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
      - 3307:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
